### ISSUE TITLE
Incosistent return value

### ISSUE THREAD

**Issue by ghost** [JlnWntr/Lua-Adapter#2]
I noticed that LuaAdapter::Load() returns false upon success, while every other method within the LuaAdapter class returns true upon success.

**Comment by JlnWntr** [comment]
`if ((luaL_loadfile(this->Lua, filename) == 0) && this->Eval()) {
    return true;
  }`
It does return true on success right at the beginning from the load-function. Otherwise an error-message would be printed via std:cout. Have you noticed this message in your console?

I can't see how you could trigger a different behavior. Can you please provide a proper source-code context?

**Comment by ghost** [comment]
I'd like to apologize, I got it backwards. It seems everything else returns
false when ::Load() returns true.

**Comment by JlnWntr** [comment]
No problem.
